version: 2
jobs:
  build:

    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: run lint
          command: ./gradlew lint

      - run:
          name: Creo cartella per risultati Lint
          command : |
               mkdir -p risultatiLintTest
               cp -R app/build/reports/lint-results.html risultatiLintTest
               cp -R app/build/reports/lint-results.xml risultatiLintTest

       - store_artifacts:
          path: risultatiLintTest
          destination: risultatiLintTest